services:
  musica-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGO_URI=mongodb://mongodb:27017/musicadb
    depends_on:
      - mongodb
    networks:
      - musica-net

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - musica-net
    volumes:
      - mongo-data:/data/db


networks:
  musica-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  jenkins_home:
    driver: local